
-- CURDATE()
SELECT CURDATE() AS 'Data Atual';

-- CURTIME()
SELECT CURTIME() AS 'Hora Atual';

-- CURRENT_TIME()
SELECT CURRENT_TIME() AS 'Hora Atual';

-- DATE_ADD(data, interval)
SELECT DATE_ADD(CURDATE(), INTERVAL 3 DAY) AS 'Data de Vencimento';

-- DATE_SUB(data, interval)
SELECT DATE_SUB(CURDATE(), INTERVAL 10 DAY) AS 'Data de Matrícula';

-- DATEDIFF(expre1, expre2)
SELECT DATEDIFF(CURDATE(), DATE_SUB(CURDATE(), INTERVAL 10 DAY)) AS 'Dias em atraso';

-- DATE_FORMAT
SELECT DATE_FORMAT(CURDATE(), '%d/%m/%Y') AS 'Data Atual';

-- DAYNAME
SELECT DAYNAME(CURDATE()) AS 'Dia da Semana';

-- DAYOFMONTH
SELECT DAYOFMONTH(CURDATE()) AS 'Dia do Mês';

-- DAYOFWEEK
SELECT DAYOFWEEK(CURDATE()) AS 'Dia do semana';

-- DAYOFYEAR
SELECT DAYOFYEAR(CURDATE()) AS 'Dia do ano';

-- FROM_DAYS
SELECT FROM_DAYS(780500) AS 'Data Real';

-- NOW()
SELECT NOW() AS 'Data/Hora Atual';

-- DATE_FORMAT
SELECT DATE_FORMAT(NOW(), '%d/%m/%Y %H:%m:%s') AS 'Data Atual';

-- CURRENT_TIMESTAMP
SELECT DATE_FORMAT(CURRENT_TIMESTAMP(), '%d/%m/%Y %H:%m:%s') AS 'Data/Hora Atual';

-- TIME()
SELECT TIME(CURRENT_TIMESTAMP()) AS 'Hora';

-- SEC_TO_TIME
SELECT SEC_TO_TIME(2000) AS 'Tempo Total';

-- TIME_TO_SEC
SELECT TIME_TO_SEC('22:32:44') AS 'Em segundos';

-- Hora, min, seg separadamente
SELECT HOUR('22:32:44') AS Hora, MINUTE('22:32:44') AS Minutos, SECOND('22:32:44') AS Segundos;

-- PERIOD_DIFF
SELECT PERIOD_DIFF(201912, 201905) AS 'Meses Restantes';

-- TIMEDIFF
SELECT TIMEDIFF('22:35:44', '22:32:55') AS Diferenca;

-- QUARTER
SELECT QUARTER('2019-03-17') AS 'Trimeste do ano';

-- WEEK
SELECT WEEK('2019-03-17') AS 'Semana do Ano';

-- WEEKDAY
SELECT WEEKDAY('2019-03-17') AS 'Dia da Semana';

-- YEAR
SELECT YEAR('2019-03-17') AS 'Ano';

-- MONTH
SELECT MONTH('2019-03-17') AS 'Mês';

-- DAY
SELECT DAY(NOW()) AS 'Dia';











